# Build tools Dockerfile v3
image: quay.io/pantheon-public/build-tools-ci:4.x

# Default Variables
variables:
  BASH_ENV: $HOME/.bashrc
  CI_BUILD_NUMBER: $CI_JOB_ID
  PR_NUMBER: $CI_MERGE_REQUEST_IID
  CI_BRANCH: $CI_COMMIT_REF_NAME

# Cache libraries in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - vendor/
  - /composer/cache
  - $HOME/.composer/cache

stages:
- build
- test
- cleanup

before_script:
- /build-tools-ci/scripts/set-environment
- source $BASH_ENV
- echo "Target site.env is $TERMINUS_SITE.$TERMINUS_ENV"
# See https://docs.gitlab.com/ee/ci/ssh_keys/README.html
- eval $(ssh-agent -s) && ssh-add <(echo "$SSH_PRIVATE_KEY")
- ./ci/scripts/01-prepare
- composer -n build-assets

deploy:multidev:
  stage: build
  environment:
    name: review/pr-$CI_MERGE_REQUEST_IID
    url: https://pr-$CI_MERGE_REQUEST_IID-$TERMINUS_SITE.pantheonsite.io/
  script:
  - echo "Target site.env is $TERMINUS_SITE.$TERMINUS_ENV"
  - ./.ci/scripts/02-init-site-under-test-clone-existing
  only:
  - merge_requests

deploy:dev:
  stage: build
  environment:
    name: dev
    url: https://dev-$TERMINUS_SITE.pantheonsite.io/
  script:
  - terminus build-env:push-code $TERMINUS_SITE.dev
  only:
  - master

test:code_sniff_unit_test:
  stage: test
  script:
  - composer install --no-ansi --no-interaction --optimize-autoloader --no-progress
  - rm -rf web
  - git checkout -- web
  - composer -n lint
  - composer -n code-sniff
  - composer -n unit-test
  only:
  - merge_requests
  - master

test:behat:
  stage: test
  script:
  - composer install --no-ansi --no-interaction --optimize-autoloader --no-progress
  - ./.ci/scripts/03-test
  only:
  - merge_requests
  - master

test:behat:cleanup:
  stage: cleanup
  when: always
  script:
  - ./.ci/scripts/05-merge-master
  - ./.ci/scripts/09-cleanup-fixtures
  only:
  - merge_requests
  - master
  dependencies:
  - test:behat
